apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dep
spec:
  replicas: 3
  selector:    
    matchLabels:
       type: webapp
  template:
    metadata:
      labels:
        type: webapp
    spec:
      containers:
        - name: webapp
          image: dempoappreg.azurecr.io/my-dotnet9-app:latest